name: rsync

on:
  schedule:
    - cron: '0 17 * * *'
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  archlinux:
    runs-on: [self-hosted, linux, main, socoding]
    steps:        
      - name: perform sync
        run: |
          distro="archlinux"
          /mnt/socoding/mirror-sync/bfsu-rsync.sh ${distro}
  
  archlinuxcn:
    runs-on: [self-hosted, linux, main, socoding]
    steps:        
      - name: perform sync
        run: |
          distro="archlinuxcn"
          /mnt/socoding/mirror-sync/bfsu-rsync.sh ${distro}

  manjaro:
    runs-on: [self-hosted, linux, main, socoding]
    steps:        
      - name: perform sync
        run: |
          distro="manjaro"
          /mnt/socoding/mirror-sync/bfsu-rsync.sh ${distro}
